name: Build Server

on:
  workflow_call:
    secrets:
      NEXUS_PASSWORD:
        required: true
      NEXUS_SETTINGS:
        required: true

jobs:
  build-server:
    runs-on: ubuntu-latest
    env:
      CI: true
      SKIP_PUBLISH: true
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_SETTINGS: ${{ secrets.NEXUS_SETTINGS }}
      working-directory: postit-server

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: "temurin"
          cache: "maven"

      - name: Init script
        run: |
          branch=$GITHUB_REF_NAME
          if [[ "$branch" = "master" ]]; then
            ./version.sh remove-snapshot
          fi
          if [[ "$branch" = "master" || "$branch" = "develop" ]]; then
            echo "PUBLISH=OK" >> $GITHUB_ENV
          fi
          mkdir -p ~/.m2
          echo $NEXUS_SETTINGS > ~/.m2/settings.xml

      - name: Test
        run: make test
        working-directory: ${{ env.working-directory }}

      - name: Build Only
        if: ${{ ! env.PUBLISH || env.SKIP_PUBLISH == 'true' }}
        run: make buildOnly
        working-directory: ${{ env.working-directory }}

      - name: Build and Archiving
        if: ${{ env.PUBLISH && env.SKIP_PUBLISH != 'true' }}
        run: make build
        working-directory: ${{ env.working-directory }}

      - name: Containerize and Publish image
        if: ${{ env.PUBLISH && env.SKIP_PUBLISH != 'true' }}
        run: make containerize
        working-directory: ${{ env.working-directory }}
