name: Build Client

on:
  workflow_call:
    secrets:
      NEXUS_PASSWORD:
        required: true

jobs:
  build-client:
    runs-on: ubuntu-latest
    env:
      CI: true
      SKIP_PUBLISH: true
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      working-directory: postit-client

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Init script
        run: |
          branch=$GITHUB_REF_NAME
          if [[ "$branch" = "master" ]]; then
            ./version.sh remove-snapshot
          fi
          if [[ "$branch" = "master" || "$branch" = "develop" ]]; then
            echo "PUBLISH=OK" >> $GITHUB_ENV
          fi

      - name: Test
        run: make test
        working-directory: ${{ env.working-directory }}

      - name: Build Only
        if: ${{ ! env.PUBLISH || env.SKIP_PUBLISH == 'true' }}
        run: make buildOnly
        working-directory: ${{ env.working-directory }}

      - name: Build and Archiving
        if: ${{ env.PUBLISH && env.SKIP_PUBLISH != 'true' }}
        run: make build
        working-directory: ${{ env.working-directory }}

      - name: Containerize and Publish image
        if: ${{ env.PUBLISH && env.SKIP_PUBLISH != 'true' }}
        run: make containerize
        working-directory: ${{ env.working-directory }}
