name: Main CI

on:
  push:
    branches:
      - "**"

jobs:
  prepare:
    runs-on: ubuntu-latest
    env:
      SKIP_DEPLOY: true
    outputs:
      deploy: ${{ steps.init.outputs.DEPLOY }}
      serverVersion: ${{ steps.init.outputs.SERVER_VERSION }}
      clientVersion: ${{ steps.init.outputs.CLIENT_VERSION }}
      skip_deploy: ${{ env.SKIP_DEPLOY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Init script
        id: init
        run: |
          branch=$GITHUB_REF_NAME
          echo "Branch : $branch"
          deploy=""
          if [[ "$branch" = "master" || "$branch" = "develop" ]]; then
              declare -A branchWithEnv=( ["master"]="prod" ["develop"]="qa" )
              deploy="${branchWithEnv[$branch]}"
          fi
          echo "Deploy: $deploy"
          echo "DEPLOY=$deploy" >> $GITHUB_OUTPUT
          if [[ "$branch" = "master" ]]; then
            ./version.sh remove-snapshot
          fi
          serverVersion=$(./version.sh list server)
          echo "Server Version : $serverVersion"
          echo "SERVER_VERSION=$serverVersion" >> $GITHUB_OUTPUT
          clientVersion=$(./version.sh list client)
          echo "Client Version : $clientVersion"
          echo "CLIENT_VERSION=$clientVersion" >> $GITHUB_OUTPUT

  build-server:
    needs: [prepare]
    uses: ./.github/workflows/build-server.yml
    secrets:
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_SETTINGS: ${{ secrets.NEXUS_SETTINGS }}

  build-client:
    needs: [prepare]
    uses: ./.github/workflows/build-client.yml
    secrets:
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

  deploy:
    needs: [prepare, build-server, build-client]
    if: ${{ needs.prepare.outputs.deploy && needs.prepare.outputs.skip_deploy != 'true' }}
    uses: ./.github/workflows/deploy.yml
    with:
      deploy: ${{ needs.prepare.outputs.deploy }}
      serverVersion: ${{ needs.prepare.outputs.serverVersion }}
      clientVersion: ${{ needs.prepare.outputs.clientVersion }}
    secrets:
      QA_SSH_HOST: ${{ secrets.QA_HOST }}
      QA_SSH_KEY: ${{ secrets.QA_SSH_KEY }}
      PROD_SSH_HOST: ${{ secrets.PROD_HOST }}
      PROD_SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
